version: '3.9'
services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: queue_db
      MYSQL_USER: queue_user
      MYSQL_PASSWORD: queue_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./data:/var/lib/mysql
  frontend:
    container_name: frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: backend
    build: ./api/
    ports:
      - '5000:5000'
    depends_on:
      - mysql
      - redis
      - frontend
  redis:
    container_name: redis
    image: 'redis:alpine'
    ports:
      - '6379:6379'
  workers:
    build:
      context: ./api/
      dockerfile: Dockerfile.worker
    depends_on:
      - mysql
      - backend
      - redis
